# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_videoresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='restaurant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='management.Restaurant'),
            preserve_default=False,
        ),
    ]
