# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-12 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_auto_20160911_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='season',
            name='name_es',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Name'),
        ),
    ]
