# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-24 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_auto_20170224_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openinghours',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='management.Season', verbose_name='Season'),
        ),
    ]
