# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 10:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_dish_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageresource',
            name='ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name=b'Punto de inter\xc3\xa9s'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Restaurant', verbose_name='Restaurante'),
        ),
        migrations.AlterField(
            model_name='imageresource',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=b'Alto'),
        ),
        migrations.AlterField(
            model_name='imageresource',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(height_field=b'height', upload_to=b'images/', verbose_name=b'Imagen', width_field=b'width'),
        ),
        migrations.AlterField(
            model_name='imageresource',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=b'Ancho'),
        ),
    ]
