# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20160718_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='openinghours',
            old_name='restaurant',
            new_name='temporada',
        ),
    ]
