# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 18:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_auto_20160718_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(blank=True, help_text=b'Otra informaci\xc3\xb3n adicional', max_length=200, null=True, verbose_name=b'Linea 2 de direcci\xc3\xb3n')),
                ('city', models.CharField(max_length=200, verbose_name=b'Ciudad')),
                ('state', models.CharField(max_length=200, verbose_name=b'Provincia')),
                ('postal_code', models.CharField(max_length=200, verbose_name=b'C\xc3\xb3digo postal')),
                ('pais', models.CharField(max_length=200, verbose_name=b'Pais')),
                ('telephone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message=b"El n\xc3\xbamero de telefono debe tener el siguiente formato: '+999999999'. No m\xc3\xa1s de 15 d\xc3\xadgitos", regex=b'^\\+?1?\\d{9,15}$')], verbose_name=b'Telefono')),
            ],
            options={
                'verbose_name': 'Restaurante',
                'verbose_name_plural': 'Restaurantes',
            },
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='address',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='telephone',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='address',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Restaurant'),
        ),
    ]
