# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 17:48
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_auto_20160718_2023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='dayclosed',
            options={'verbose_name': 'Day closed', 'verbose_name_plural': 'Days closed'},
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name': 'Dish', 'verbose_name_plural': 'Dishes'},
        ),
        migrations.AlterModelOptions(
            name='imageresource',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='openinghours',
            options={'verbose_name': 'Opening hours', 'verbose_name_plural': 'Opening hours'},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name': 'Restaurant', 'verbose_name_plural': 'Restaurant'},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'verbose_name': 'Season', 'verbose_name_plural': 'Seasons'},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'verbose_name': 'Time slot', 'verbose_name_plural': 'Time slots'},
        ),
        migrations.RemoveField(
            model_name='openinghours',
            name='temporada',
        ),
        migrations.AddField(
            model_name='openinghours',
            name='season',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='management.Season', verbose_name='Season'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=200, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='address',
            name='line1',
            field=models.CharField(help_text='Street and number, post office box, company name', max_length=200, verbose_name='Line 1'),
        ),
        migrations.AlterField(
            model_name='address',
            name='line2',
            field=models.CharField(blank=True, help_text='Other additional info', max_length=200, null=True, verbose_name='Line 2'),
        ),
        migrations.AlterField(
            model_name='address',
            name='pais',
            field=models.CharField(max_length=200, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=200, verbose_name='Postal code'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=200, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='address',
            name='telephone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="The phone number should have the following format: '+999999999'. 15 digits max", regex=b'^\\+?1?\\d{9,15}$')], verbose_name='Telephone'),
        ),
        migrations.AlterField(
            model_name='dayclosed',
            name='day',
            field=models.DateField(verbose_name='Day closed'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0.0'), default_currency=b'EUR', max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Publish date'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Restaurant', verbose_name='Restaurant'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='type',
            field=models.CharField(choices=[('APE', 'Snack'), ('ENT', 'Starter'), ('PRI', 'Main'), ('POS', 'Dessert')], max_length=3, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='imageresource',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='imageresource',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(height_field=b'height', upload_to=b'images/', verbose_name='Image', width_field=b'width'),
        ),
        migrations.AlterField(
            model_name='imageresource',
            name='ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name='Point of interest'),
        ),
        migrations.AlterField(
            model_name='imageresource',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Publish date'),
        ),
        migrations.AlterField(
            model_name='imageresource',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='imageresource',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Width'),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='weekdays',
            field=models.CharField(choices=[(b'lu', 'Monday'), (b'ma', 'Tuesday'), (b'mx', 'Wednesday'), (b'ju', 'Thursday'), (b'vi', 'Friday'), (b'sa', 'Saturday'), (b'do', 'Sunday')], help_text='Weeksdays in which the schedule applies', max_length=100, verbose_name='Weekdays'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='season',
            name='begin',
            field=models.DateField(help_text='Season begin date', verbose_name='Begin'),
        ),
        migrations.AlterField(
            model_name='season',
            name='end',
            field=models.DateField(help_text='Season end date', verbose_name='End'),
        ),
        migrations.AlterField(
            model_name='season',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='begin',
            field=models.TimeField(verbose_name='Begin'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end',
            field=models.TimeField(verbose_name='End'),
        ),
        migrations.AlterField(
            model_name='videoresource',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Publish date'),
        ),
        migrations.AlterField(
            model_name='videoresource',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title'),
        ),
    ]
