# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-12 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_auto_20160912_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageresource',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='imageresource',
            name='title_es',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='videoresource',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='videoresource',
            name='title_es',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title'),
        ),
    ]
