# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-23 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_auto_20160912_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='pais',
            new_name='country',
        ),
        migrations.AlterField(
            model_name='address',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='management.Restaurant'),
        ),
    ]
