# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-12 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_auto_20161023_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageresource',
            name='main',
            field=models.BooleanField(default=False, help_text='This a main representative picture that can be used for thumbnails', verbose_name='Main picture'),
        ),
    ]
