# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-02 09:30
from __future__ import unicode_literals

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_auto_20170224_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='location',
            field=location_field.models.plain.PlainLocationField(default=0, max_length=63, verbose_name='Location'),
            preserve_default=False,
        ),
    ]
